openapi: 3.1.1
info:
  title: Musicband Service Endpoints - OpenAPI 3.1.1
  description: |-
    **OpenAPI** specification for **Laboratory work №1** of **Service-oriented architecture** at **ITMO-University**.
  contact:
    name: Roman Kobelev & Balin Artem
    url: https://github.com/ta4ilka69/Service-oriented-architecture
  license:
    name: The MIT License
    url: https://mit-license.org/
  version: 0.0.1
servers:
  - url: https://se.ifmo.ru
    description: Helios
components:
  schemas:
    Album:
      type: object
      properties:
        name:
          type: string
          minLength: 1
        tracks:
          type: integer
          format: int64
          minimum: 1
      required:
        - name
        - tracks
    Coordinates:
      type: object
      properties:
        x:
          type: number
          format: float
          exclusiveMinimum: -975
        y:
          type: integer
          format: int64
          minimum: 1
      required:
        - x
        - y
    MusicBand:
      type: object
      xml:
        name: musicBand
      properties:
        id:
          type: integer
          format: int32
          minimum: 1
        name:
          type: string
          minLength: 1
        coordinates:
          $ref: '#/components/schemas/Coordinates'
        creationDate:
          type: string
          format: date
        numberOfParticipants:
          type: integer
          format: int32
          minimum: 1
        albumsCount:
          type: integer
          format: int32
          minimum: 1
        description:
          type: string
          minLength: 0
        genre:
          type: string
          enum:
            - PSYCHEDELIC_CLOUD_RAP
            - SOUL
            - POP
        bestAlbum:
          $ref: '#/components/schemas/Album'
          nullable: true
      required:
        - id
        - name
        - coordinates
        - creationDate
        - numberOfParticipants
        - albumsCount
        - description
        - genre
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
          example: 500
        message:
          type: string
          example: Internal Server Error
