openapi: 3.1.1

info:
  title: Musicband Service Endpoints - OpenAPI 3.1.1

  description: |-
    **OpenAPI** specification for **Laboratory work №1** of **Service-oriented architecture** at **ITMO-University**.

  contact:
    name: Roman Kobelev & Balin Artem
    url: https://github.com/ta4ilka69/Service-oriented-architecture

  license:
    name: The MIT License
    url: https://mit-license.org/

  version: 0.0.1

servers:
  - url: 'https://localhost:5252'
    description: Helios

paths:
  /music-bands:
    get:
      summary: Get list of musicbands.
      description: Get list of musicbands with possible filtering, sorting and pagination.

      parameters:
        - name: sort
          in: query
          description: Fields to sort by. Prefix with '-' for descending order. If field is used multiple times (both with and without prefix), the last occurrence takes precedence.
          required: false
          schema:
            type: array
            items:
              $ref: '#/components/schemas/SortValues'

        - name: page
          in: query
          description: Page number. If provided, size must also be provided. Otherwise, page is ignored.
          required: false
          schema:
            type: integer
            format: int32
            minimum: 1
            default: 1

        - name: size
          in: query
          description: Number of items per page. If page is provided, size must also be provided. Otherwise, size is ignored.
          required: false
          schema:
            type: integer
            format: int32
            minimum: 1
            default: 10

        - name: filter
          in: query
          description: Filter conditions in the format field(>=|<=|>|<|!=|==|^=|$=|@=)value. "^=" is for prefix matching, "$=" is for suffix matching, and "@=" is for substring matching. If a non-numeric field is used with a numeric operator or date format is invalid, an error is returned.
          required: false
          schema:
            type: array
            items:
              $ref: '#/components/schemas/FilterCondition'

      responses:
        '200':
          description: A list of musicbands.
          content:
            application/xml:
              schema:
                type: array
                xml:
                  name: musicBands
                  wrapped: true
                items:
                  $ref: '#/components/schemas/MusicBandAllSchema'

        '400':
          $ref: '#/components/responses/BadRequestInvalidQueryParameters'
        '500':
          $ref: '#/components/responses/InternalServerError'
        default:
          description: Internal Server Error
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Error'

    post:
      summary: Create a new musicband.
      description: Create a new musicband with the provided details.

      requestBody:
        description: Musicband to add.
        required: true
        content:
          application/xml:
            schema:
              $ref: '#/components/schemas/MusicBand'

      responses:
        '201':
          description: Musicband created successfully.
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/MusicBandAllSchema'

        '400':
          $ref: '#/components/responses/BadRequestInvalidInput'

        '500':
          $ref: '#/components/responses/InternalServerError'
        default:
          description: Internal Server Error
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Error'

  /music-bands/{id}:
    get:
      summary: Get a musicband by ID.
      description: Retrieve a single musicband by its unique ID.

      parameters:
        - name: id
          in: path
          description: The unique identifier of the musicband.
          required: true
          schema:
            $ref: '#/components/schemas/MusicBandId'

      responses:
        '200':
          description: A single musicband.
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/MusicBandAllSchema'

        '400':
          $ref: '#/components/responses/BadRequestInvalidID'

        '404':
          $ref: '#/components/responses/MusicBandNotFound'
        '422':
          $ref: '#/components/responses/InvalidIdFormat'

        '500':
          $ref: '#/components/responses/InternalServerError'
        default:
          description: Internal Server Error
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Error'

    put:
      summary: Update an existing musicband (with all fields).
      description: Update an existing musicband by its ID. All fields must be provided. Missing fields will be set to null.

      parameters:
        - name: id
          in: path
          description: The unique identifier of the musicband to update.
          required: true
          schema:
            $ref: '#/components/schemas/MusicBandId'

      requestBody:
        description: Updated musicband details.
        required: true
        content:
          application/xml:
            schema:
              $ref: '#/components/schemas/MusicBand'

      responses:
        '200':
          description: Musicband updated successfully.
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/MusicBandAllSchema'

        '400':
          $ref: '#/components/responses/BadRequestInvalidInput'

        '404':
          $ref: '#/components/responses/MusicBandNotFound'

        '500':
          $ref: '#/components/responses/InternalServerError'
        default:
          description: Internal Server Error
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      summary: Delete a musicband by ID.
      description: Delete a single musicband by its unique ID.

      parameters:
        - name: id
          in: path
          description: The unique identifier of the musicband to delete.
          required: true
          schema:
            $ref: '#/components/schemas/MusicBandId'

      responses:
        '204':
          description: Musicband deleted successfully. No content returned.

        '400':
          $ref: '#/components/responses/BadRequestInvalidID'

        '404':
          $ref: '#/components/responses/MusicBandNotFound'

        '500':
          $ref: '#/components/responses/InternalServerError'
        default:
          description: Internal Server Error
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Error'

    patch:
      summary: Partially update a musicband by ID.
      description: Update one or more fields of an existing musicband by its ID. Only the provided fields will be updated; other fields will remain unchanged.

      parameters:
        - name: id
          in: path
          description: The unique identifier of the musicband to update.
          required: true
          schema:
            $ref: '#/components/schemas/MusicBandId'
      requestBody:
        description: Fields to update in the musicband.
        required: true
        content:
          application/xml:
            schema:
              $ref: '#/components/schemas/MusicBandPatch'
      responses:
        '200':
          description: Musicband updated successfully.
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/MusicBandAllSchema'

        '400':
          $ref: '#/components/responses/BadRequestInvalidInput'

        '404':
          $ref: '#/components/responses/MusicBandNotFound'

        '500':
          $ref: '#/components/responses/InternalServerError'
        default:
          description: Internal Server Error
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Error'

  /music-bands/all-with-description:
    delete:
      summary: Delete all musicbands with a specific description.
      description: Delete all musicbands whose description matches the provided value. If nothing is deleted, it means success too.

      parameters:
        - name: description
          in: query
          description: The description to filter musicbands for deletion.
          required: true
          schema:
            $ref: '#/components/schemas/MusicBandDescription'

      responses:
        '204':
          description: Musicbands deleted successfully. No content returned.

        '400':
          description: Bad Request - Missing or invalid description parameter.
          $ref: '#/components/responses/BadRequestInvalidQueryParameters'

        '500':
          $ref: '#/components/responses/InternalServerError'
        default:
          description: Internal Server Error
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Error'

  /music-bands/one-with-genre:
    delete:
      summary: Delete one musicband with a specific genre.
      description: Delete one random musicband whose genre matches the provided value. Input is case-sencetive. If nothing is deleted, it means success too.

      parameters:
        - name: genre
          in: query
          description: The genre to filter musicbands for deletion.
          required: true
          schema:
            $ref: '#/components/schemas/MusicBandGenre'

      responses:
        '204':
          description: Musicband deleted successfully. No content returned.

        '400':
          description: Bad Request - Missing or invalid genre parameter.
          $ref: '#/components/responses/BadRequestInvalidQueryParameters'

        '500':
          $ref: '#/components/responses/InternalServerError'
        default:
          description: Internal Server Error
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Error'

  /music-bands/count-best-album:
    get:
      summary: Count musicbands with best album greater than provided.
      description: Get the count of musicbands whose best album has more tracks than the specified number. If equals, uses alphabetical comparison of the names.

      parameters:
        - name: albumName
          in: query
          required: true
          description: The name of the album to compare against.
          schema:
            type: string
            minLength: 1
        - name: albumTracks
          in: query
          required: true
          description: The number of tracks in the album to compare against.
          schema:
            type: integer
            format: int64
            minimum: 1

      responses:
        '200':
          description: Count of musicbands with best album tracks greater than the specified number.
          content:
            application/xml:
              schema:
                xml:
                  name: count
                type: integer
                format: int64
                example: 5

        '400':
          description: Bad Request - Missing or invalid tracks parameter.
          $ref: '#/components/responses/BadRequestInvalidQueryParameters'

        '500':
          $ref: '#/components/responses/InternalServerError'
        default:
          description: Internal Server Error
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Album:
      type: object
      xml:
        name: album
      properties:
        name:
          type: string
          minLength: 1
        tracks:
          type: integer
          format: int64
          minimum: 1
      required:
        - name
        - tracks

    Coordinates:
      type: object
      properties:
        x:
          type: number
          format: float
          exclusiveMinimum: -975
        y:
          type: integer
          format: int64
          minimum: 1
      required:
        - x
        - y

    MusicBand:
      type: object
      xml:
        name: musicBand
      properties:
        name:
          type: string
          minLength: 1
        coordinates:
          $ref: '#/components/schemas/Coordinates'
        numberOfParticipants:
          type: integer
          format: int32
          minimum: 1
        albumsCount:
          type: integer
          format: int32
          minimum: 1
        description:
          $ref: '#/components/schemas/MusicBandDescription'
        genre:
          $ref: '#/components/schemas/MusicBandGenre'
        bestAlbum:
          $ref: '#/components/schemas/Album'
          nullable: true
      required:
        - name
        - coordinates
        - numberOfParticipants
        - albumsCount
        - description
        - genre
    MusicBandAllSchema:
      allOf:
        - $ref: '#/components/schemas/MusicBand'
        - type: object
          required:
            - id
          properties:
            id:
              type: integer
              format: int32
              minimum: 1
            creationDate:
              type: string
              format: date
      xml:
        name: musicBandAllSchema
    MusicBandPatch:
      type: object
      xml:
        name: musicBand
      properties:
        name:
          type: string
          minLength: 1
        coordinates:
          $ref: '#/components/schemas/Coordinates'
        numberOfParticipants:
          type: integer
          format: int32
          minimum: 1
        albumsCount:
          type: integer
          format: int32
          minimum: 1
        description:
          $ref: '#/components/schemas/MusicBandDescription'
        genre:
          $ref: '#/components/schemas/MusicBandGenre'
        bestAlbum:
          $ref: '#/components/schemas/Album'
          nullable: true

    Error:
      type: object
      required:
        - code
        - message
      xml:
        name: error
      properties:
        code:
          type: integer
          format: int32
          example: 500
        message:
          type: string
          example: Internal Server Error

    InternalServerError:
      allOf:
        - $ref: '#/components/schemas/Error'
        - type: object
          properties:
            code:
              example: 500
            message:
              example: Internal Server Error
    NotFoundError:
      allOf:
        - $ref: '#/components/schemas/Error'
        - type: object
          properties:
            code:
              example: 404
            message:
              example: Not Found
    BadRequestError:
      allOf:
        - $ref: '#/components/schemas/Error'
        - type: object
          properties:
            code:
              example: 400
            message:
              example: Bad Request
    UnprocessableEntityError:
      allOf:
        - $ref: '#/components/schemas/Error'
        - type: object
          properties:
            code:
              example: 422
            message:
              example: Unprocessable Entity

    FilterCondition:
      type: string
      pattern: '^((name|creationDate|description|genre|bestAlbum\.name)(>=|<|>|<=|!=|==|^=|$=|@=).+)|(coordinates\.x(>=|<=|>|<|!=|==)-?\d+(\.\d+)?|(id|coordinates\.y|numberOfParticipants|albumsCount|bestAlbum\.tracks)(>=|<=|>|<|!=|==)-?\d+)$'

    SortValues:
      type: string
      pattern: '^(id|-id|name|-name|coordinates\.x|-coordinates\.x|coordinates\.y|-coordinates\.y|creationDate|-creationDate|numberOfParticipants|-numberOfParticipants|albumsCount|-albumsCount|description|-description|genre|-genre|bestAlbum\.name|-bestAlbum\.name|bestAlbum\.tracks|-bestAlbum\.tracks)$'

    PatchOption:
      type: string
      xml:
        name: field
      pattern: '^((name|creationDate|description|genre|bestAlbum\.name)=.+)|(coordinates\.x=-?\d+(\.\d+)?|(id|coordinates\.y|numberOfParticipants|albumsCount|bestAlbum\.tracks)=-?\d+)$'

    MusicBandId:
      type: integer
      format: int32
      minimum: 1

    MusicBandDescription:
      type: string
      minLength: 0

    MusicBandGenre:
      type: string
      enum:
        - PSYCHEDELIC_CLOUD_RAP
        - SOUL
        - POP

  responses:
    InternalServerError:
      description: Internal Server Error
      content:
        application/xml:
          schema:
            $ref: '#/components/schemas/InternalServerError'

    MusicBandNotFound:
      description: Not Found - Musicband not found.
      content:
        application/xml:
          schema:
            $ref: '#/components/schemas/NotFoundError'

    BadRequestInvalidID:
      description: Bad Request - Invalid ID supplied.
      content:
        application/xml:
          schema:
            $ref: '#/components/schemas/BadRequestError'
    BadRequestInvalidQueryParameters:
      description: Bad Request - Invalid Query Parameters.
      content:
        application/xml:
          schema:
            $ref: '#/components/schemas/BadRequestError'

    BadRequestInvalidInput:
      description: Bad Request - Invalid input.
      content:
        application/xml:
          schema:
            $ref: '#/components/schemas/BadRequestError'

    InvalidIdFormat:
      description: Parameter 'id' must be a positive integer.
      content:
        application/xml:
          schema:
            $ref: '#/components/schemas/UnprocessableEntityError'
