openapi: 3.1.1
info:
  title: Swagger Musicband Controller - OpenAPI 3.1.1
  description: |-
    **OpenAPI** specification for **Laboratory work №1** of **Service-oriented architecture** at **ITMO-University**.
  contact:
    name: Roman Kobelev & Balin Artem
    url: 
  version: 0.0.1