spring.application.name=api-gateway
spring.config.import=optional:configserver:http://localhost:7843

logging.level.ru.itmo.soa.gateway=INFO
logging.level.org.springframework.cloud.loadbalancer=INFO
logging.level.org.springframework.cloud.gateway=INFO