rest.port=5300
mule.truststore.path=/home/studs/s367854/mule-enterprise-standalone-4.10.1/conf/truststore.jks
mule.truststore.pass=q23886000
mule.keystore.path=/home/studs/s367854/mule-enterprise-standalone-4.10.1/conf/server2.p12
mule.keystore.pass=q23886000


